spring.application.name=payment-system

asaas.api.token.prod=$aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjBmNGY1NDc5LTFlYmEtNDg1My1iNzBhLWVmNjU4Mzc5ZTA4ODo6JGFhY2hfYzcyYWM1ZjItMGZhNy00MDNiLWJlMjMtYzM3YjhkYjRiMWQx
asaas.api.token.homo=$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjlhYzczZWVlLTJmOGYtNDM4OC1hNjE5LTk2ZTQ0YjBhMGE3NTo6JGFhY2hfZWY2OGFkZjMtMDZlOS00MmJhLWJhMDMtMTMxZTQ4ZjFjMjA1