spring.application.name=payment-system

asaas.api.token.prod=$aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmNhZjM5MjQwLWJhNDYtNGRlZC1hM2MwLWJlM2MwZGI0NmQ5Zjo6JGFhY2hfOGEzZmUzNzAtNThiYy00Y2Y0LTk2YTItNzBjM2EzNzdkOGM3
asaas.api.token.homo=$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjkwMTVlYTcwLWQzYTgtNDdjMi1iZDRkLTZlNWNkODYyZGZmNTo6JGFhY2hfMGQyNWViOWYtNjM1ZC00NTkyLWI2YmItMjlkYzgyOTQ5YTc1

